### ISSUE TITLE
Disabled facebook button has white text and icon.

### ISSUE THREAD

**Issue by pauldemarco** [elbeicktalat/flutter_auth_buttons#1]
When the "Sign in with Facebook" button is disabled (onPressed == null), the text and icon color remain white.
Expected operation was for the text and icon color to dim out to near black, similar to the "Sign in with Google/Apple" buttons.

P.S. Thanks a bunch for this wonderful package!

**Comment by elbeicktalat** [comment]
**Thank you** for using our package!
When you pass null it's insignificant, so that's way the button still gray.
But don't worry I'll see what can I do for that thanks.
