### ISSUE TITLE
facebook new color 

### ISSUE THREAD

**Issue by sowsan** [elbeicktalat/flutter_auth_buttons#19]
First thank you so much for publishing these package :) 

How e can make the icon and button with the new facebook design guideline on color?

https://developers.facebook.com/docs/facebook-login/userexperience/

**Comment by elbeicktalat** [comment]
@sowsan Thank you man,
For the icons I'll update those quickly, but for the button color you don't need to await me just use `style` staff specifically `buttonColor` and you'll done.

**Comment by elbeicktalat** [comment]
This is related to: #24
