### ISSUE TITLE
Progress indicator sizing

### ISSUE THREAD

**Issue by manafire** [elbeicktalat/flutter_auth_buttons#20]
Thank you for contributing this package.  

There's quite a noticeable difference between the icon and when it's in a loading state:

<img width="474" alt="normal" src="https://user-images.githubusercontent.com/432876/115975459-e2fb4d00-a532-11eb-92cb-cbab5f0f6494.png">

<img width="476" alt="loading" src="https://user-images.githubusercontent.com/432876/115975462-e5f63d80-a532-11eb-8bf1-5c640552d000.png">

```
  GoogleAuthButton(
    isLoading: true,
    onPressed: onSignInWithGoogle!,
    text: 'Continue with Google',
    style: AuthButtonStyle(
      buttonColor: Color(0xff4285F4),
      iconBackground: Colors.white,
      iconSize: 24,
      height: 50,
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      textStyle: TextStyle(color: Colors.white),
      buttonType: AuthButtonType.secondary,
    ),
  ),
```

I've tightened the UI up for my own use but will submit a PR if you're interested.

<img width="477" alt="fixed" src="https://user-images.githubusercontent.com/432876/115975535-a11ed680-a533-11eb-8888-d3a384f2982a.png">

**Comment by elbeicktalat** [comment]
@manafire Nice job thanks!
