### ISSUE TITLE
"6 widgets with key [<'GoogleAuthButton'>]" - testing finder error

### ISSUE THREAD

**Issue by idotalmor** [elbeicktalat/flutter_auth_buttons#28]
Hi!
This library builds the auth buttons by composing multiple widgets with the same key, which makes it impossible to grab the widgets by its key for testing purposes.

please add support for testing in your roadmap. also, I think multiple keys can lead to rendering issues with the flutter engine.

**Comment by elbeicktalat** [comment]
Hi there,
You are right and actually I'm working for better testing and debugging support.

**Comment by elbeicktalat** [comment]
The all authentication buttons are covered by widget tests, so I think you don't need to test nothing. if you have a critical need try `find.byType` in your test.
