### ISSUE TITLE
Update to flutter_svg 1.0.0

### ISSUE THREAD

**Issue by marcoberetta96** [elbeicktalat/flutter_auth_buttons#41]
Can this package be updated to the new stable flutter_svg 1.0.0?

**Comment by elbeicktalat** [comment]
Of course,
As you know flutter_svg package was released a couple of days ago.

**Comment by marcoberetta96** [comment]
Hi @elbeicktalat could you please update the package also un pub.dev to depend on flutter_svg 1.0.0?
Thank you.
