### ISSUE TITLE
iconColor attribute not working on GoogleAuthButton in AuthButtonStyle.secondary

### ISSUE THREAD

**Issue by S0NN1** [elbeicktalat/flutter_auth_buttons#42]
Hi,
I was tweaking the GoogleAuthButton and I found an incorrect behavior:
The following code works as expected
```dart
GoogleAuthButton(
          darkMode: true,
          onPressed: () async {
            // do something
          },
          style: AuthButtonStyle(
                      padding: EdgeInsets.fromLTRB(0, 0, 25, 0),
                      separator: 11,
                      buttonColor: Theme.of(context).cardColor,
                      iconColor: Colors.white,
                      iconBackground: Theme.of(context).cardColor,
                      buttonType: AuthButtonType.icon,
                      borderColor: Theme.of(context).colorScheme.secondary,
                      elevation: 0,
                      textStyle: TextStyle(color: Colors.white)),
        ),
```
![image](https://user-images.githubusercontent.com/40118754/149669705-aa8ebd0a-7551-41f0-9855-199d4c69f631.png)
Meanwhile if I select the AuthButtonStyle.secondary attribute instead, the iconColor specified is ignored
```dart
GoogleAuthButton(
          darkMode: true,
          onPressed: () async {
            // do something
          },
          style: AuthButtonStyle(
                      padding: EdgeInsets.fromLTRB(0, 0, 25, 0),
                      separator: 11,
                      buttonColor: Theme.of(context).cardColor,
                      iconColor: Colors.white,
                      iconBackground: Theme.of(context).cardColor,
                      buttonType: AuthButtonType.secondary,
                      borderColor: Theme.of(context).colorScheme.secondary,
                      elevation: 0,
                      textStyle: TextStyle(color: Colors.white)),
        ),
```
![image](https://user-images.githubusercontent.com/40118754/149669760-cd459e9a-7087-4693-89e7-0d707f2be32f.png)
The other buttons work as expected
![image](https://user-images.githubusercontent.com/40118754/149669777-bddbd2a5-c9d6-482c-9fa8-9b2d7e9929fe.png)
Shouldn't it be customizable?

**Comment by S0NN1** [comment]
I forgot to mention that I'm using the latest version: auth_buttons 2.0.4 with flutter 2.8.1

**Comment by elbeicktalat** [comment]
Hi @S0NN1,
Thanks for your issue.

Of course this should be customizable as much as possible, clearly this is a bug which I will fix it as much as possible.

**Comment by elbeicktalat** [comment]
Hi @S0NN1 

I have fixed this,
**NOTE**: Only secondary icons cannot be changed of color.

Thanks agin for you help.
