### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by adar2378** [elbeicktalat/flutter_auth_buttons#50]
Hi, sometimes I get this error when loading screen with AuthButtons

>>> Null check operator used on a null value, #0 RenderBox.size (package:flutter/src/rendering/box.dart:2023) #1 _ButtonContentState.getTextWidgetWidth (package:auth_buttons/src/shared/core/widgets/button_content.dart:95) #2 _ButtonContentState.initState.<anonymous closure> (package:auth_buttons/src/shared/core/widgets/button_content.dart:50) #3 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175) #4 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113) #5 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015) #6 _rootRun (dart:async/zone.dart:1391) #7 _CustomZone.run (dart:async/zone.dart:1293) #8 _CustomZone.runGuarded (dart:async/zone.dart:1201) #9 _invoke (dart:ui/hooks.dart:150) #10 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318) #11 _drawFrame (dart:ui/hooks.dart:115)

**Comment by elbeicktalat** [comment]
Hi there,
Thanks for your time,

This happened because the AuthButton is not able to get the RenderBox. This is not really an issue, but I will provide some failback value.

Thanks an good coding!

**Comment by adar2378** [comment]
@elbeicktalat I think this is a Flutter related issue https://github.com/flutter/flutter/issues/107397

A fallback value may not work due this bug.

**Comment by elbeicktalat** [comment]
I think no body facing this issue anymore, by the way it was caused to flutter.
