### ISSUE TITLE
Feature_Request: Sign in with WeChat 

### ISSUE THREAD

**Issue by johnmelodyme** [elbeicktalat/flutter_auth_buttons#53]
Consider adding SignIn with Wechat.

**Comment by elbeicktalat** [comment]
I thought I answered you,

Any way, you can create it yourself and still using this library, I did provide you with `CustomAuthButton` class which allows you to get the job on the fly also allowing you to still having advantages of the AuthButtons such as Grouping button ad having the same shared proprties.

Take a look at:
- [CustomAuthButton](https://github.com/elbeicktalat/flutter_auth_buttons/blob/main/lib/src/buttons/custom_auth_button.dart)
- [AuthButtonGroup](https://github.com/elbeicktalat/flutter_auth_buttons/blob/main/lib/src/buttons/auth_button_group.dart)

**Comment by ctkqiang** [comment]
> I thought I answered you,
> 
> 
> 
> Any way, you can create it yourself and still using this library, I did provide you with `CustomAuthButton` class which allows you to get the job on the fly also allowing you to still having advantages of the AuthButtons such as Grouping button ad having the same shared proprties.
> 
> 
> 
> Take a look at:
> 
> - [CustomAuthButton](https://github.com/elbeicktalat/flutter_auth_buttons/blob/main/lib/src/buttons/custom_auth_button.dart)
> 
> - [AuthButtonGroup](https://github.com/elbeicktalat/flutter_auth_buttons/blob/main/lib/src/buttons/auth_button_group.dart)

This is helpful !😇🙏🙏🙏
