### ISSUE TITLE
Release the latest version to pub.dev

### ISSUE THREAD

**Issue by mazzonem** [elbeicktalat/flutter_auth_buttons#54]

**Comment by akurnaz** [comment]
I get this error when I run "flutter pub get" command.

`Because app depends on auth_buttons ^3.0.0 which depends on google_fonts ^3.0.1, google_fonts ^3.0.1 is required.
So, because app depends on google_fonts ^4.0.4, version solving failed.`

**Comment by ktinguer** [comment]
@akurnaz  I' m getting the same error, any solution yet?

**Comment by JoshRice1** [comment]
Is this abandoned at this point and if so can it be transferred to someone else to maintain it and update it with flutter releases?

**Comment by elbeicktalat** [comment]
> Is this abandoned at this point and if so can it be transferred to someone else to maintain it and update it with flutter releases?

Hi there,

**Comment by elbeicktalat** [comment]
> Is this abandoned at this point and if so can it be transferred to someone else to maintain it and update it with flutter releases?

@JoshRice1 No its not abandoned, but I was so busy. I'll update it. I promise.

**Comment by elbeicktalat** [comment]
As my promise, I have updated the libraries with random improvements!
